### ISSUE TITLE
Yo generator

### ISSUE THREAD

**Issue by alexewerlof** [driftyco/ionic-heroku-button#1]
It's a very useful template. How about publishing a Yo Generator?
http://yeoman.io/generators/

**Comment by adamdbradley** [comment]
Greetings @userpixel!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
